// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID      string `json:"id"`
	Country string `json:"country"`
	State   string `json:"state"`
	Street  string `json:"street"`
}

type NewAddress struct {
	Country string `json:"country"`
	State   string `json:"state"`
	Street  string `json:"street"`
}

type NewUser struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	AddressID string `json:"addressId"`
}

type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Email   string   `json:"email"`
	Phone   string   `json:"phone"`
	Address *Address `json:"address"`
}
